channels:
  - conda-forge
  - defaults
dependencies:
  - flatten_json
  - zarr=2.13.3
  - numcodecs>=0.9.1
  - numpy>=1.26.0
  - scikit-image>=0.21.0
  - tifffile
  - pip
  - pydantic=2.7.1
  - pip:
    - argparse
    - fishspot>=0.3.0
    - opencv-python>=4.5.5.64
    - pynrrd
    - SimpleITK>=2.2.1
    - git+https://github.com/GFleishman/ClusterWrap.git@ecdcb7a
