[build-system]
requires = ["setuptools>=70", "setuptools-scm>=8"]
build-backend = "setuptools.build_meta"

[project]
name = "bigstream"
version = "5.0.2"
description = "Tools for distributed alignment of massive images"
license = "BSD-3-Clause"
requires-python = ">=3.10"
authors = [
    { name = "Greg M. Fleishman", email = "greg.nli10me@gmail.com" }
]
dependencies = [
    "numpy>2,<3",
    "scipy>=1.9.1",
    "opencv-python>=4.5.5.64",
    "dask>=2025.11.0",
    "distributed>=2025.11.0",
    "ClusterWrap>=0.3.0",
    "zarr>3,<4",
    "h5py>=3.15.1",
    "numcodecs>=0.16.1",
    "fishspot>=0.2.3",
    "SimpleITK>=2.2.0",
    "tifffile>=2025.10.16",
    "morphsnakes>=2.0.0",
    "pynrrd>=1.0.0",
    "scikit-image>=0.20.0",
]

[project.urls]
"Bug Tracker" = "https://github.com/JaneliaScicomp/bigstream/issues"

[tool.setuptools.packages.find]
where = [
    "."
]
