spot_detection: &spot_detection_args
  blob_sizes: '6,20'
  blob_method: 'log'
  threshold:
  threshold_rel: 0.1
  winsorize_limits: 0.01,0.01
  background_subtract: false

ransac: &ransac_args
  nspots: 2000
  num_sigma_max: 15
  cc_radius: 12
  match_threshold: 0.7
  max_spot_match_distance:
  point_matches_threshold: 50
  align_threshold: 2.0
  diagonal_constraint: 0.25
  fix_spots_count_threshold: 100
  fix_spot_detection_kwargs:
    <<: *spot_detection_args
  mov_spots_count_threshold: 100
  mov_spot_detection_kwargs:
    <<: *spot_detection_args

affine: &affine_args
  optimizer: LBFGS2
  metric: MMI
  sampling: 'NONE'
  interpolator: '1'
  shrink_factors:
    - 1
  smooth_sigmas:
    - 0
  metric_args: {}
  optimizer_args:
    learningRate: 0.25
    minStep: 0
    numberOfIterations: 10
  sampling_percentage:
  exhaustive_step_sizes:
  iterations: 1

deform: &deform_args
  <<: *affine_args
  control_point_spacing: 50
  control_point_levels: 1
  alignment_spacing:

rigid:
  <<: *affine_args
  rigid: true

random:
  <<: *affine_args
  use_patch_mutual_information: false
  print_running_improvements: false

global_align:
  - steps:
    - ransac
    - affine
  - ransac:
    <<: *ransac_args
  - affine:
    <<: *affine_args
    iterations: 100

local_align:
  - steps:
    - ransac
    - deform
  - ransac:
    <<: *ransac_args
  - deform:
    <<: *deform_args
    iterations: 10
