ransac:
  blob_sizes: [6, 14]
  nspots: 2000
  num_sigma_max: 7
  cc_radius: 20
  match_threshold: 0.6
  max_spot_match_distance:
  point_matches_threshold: 50
  align_threshold: 2.0
  diagonal_constraint: 0.7
  confidence: 0.999
  fix_spots_count_threshold: 50
  fix_spot_detection_kwargs:
    blob_method: log
    background_subtract: false
    threshold: 0.0001
    threshold_rel: 0.001
    winsorize_limits: [0.01, 0.01]
  mov_spots_count_threshold: 50
  mov_spot_detection_kwargs:
    blob_method: log
    background_subtract: false
    threshold: 0.001
    threshold_rel: 0.01
    winsorize_limits: [0.01, 0.01]

global_align:
  steps: [affine]
  affine:
    initial_condition: CENTER
    alignment_spacing: 4.0
    shrink_factors: [4]
    smooth_sigmas: [4]
    optimizer: RSGD
    optimizer_args:
      learningRate: 2.25
      minStep: 0.001
      numberOfIterations: 400

local_align:
  steps: [ransac, affine, deform]
  block_size: [128, 128, 128]
  block_overlap: 0.25
  transform_overlap: 0.1
  affine:
    # sampling: NONE, RANDOM, REGULAR
    sampling: NONE
    # sampling_percentage matters only for RANDOM and REGULAR
    sampling_percentage: 1.0
    alignment_spacing: 2.0
    shrink_factors: [2]
    smooth_sigmas: [2.0]
    metric: MMI
    optimizer: RSGD
    optimizer_args:
      learningRate: 0.25
      minStep: 0.001
      numberOfIterations: 200
  deform:
    sampling: NONE
    sampling_percentage: 1.0
    alignment_spacing: 1.0
    control_point_spacing: 128
    control_point_levels: [1]
    shrink_factors: [1]
    smooth_sigmas: [1.0]
    metric: MMI
    optimizer: GD
    optimizer_args:
      learningRate: 0.5
      convergenceMinimumValue: 0.0001
      numberOfIterations: 300
